// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTALwcM5wVhfPOAN72dNcYe0Z4N1BfMk',
    appId: '1:706780828460:web:61e21c41a4c425eecd9289',
    messagingSenderId: '706780828460',
    projectId: 'metqr-ff755',
    authDomain: 'metqr-ff755.firebaseapp.com',
    storageBucket: 'metqr-ff755.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATgrUpJgXKUtBYxYAxIBrot52ZAcUGvJc',
    appId: '1:706780828460:android:c2cc955d271af054cd9289',
    messagingSenderId: '706780828460',
    projectId: 'metqr-ff755',
    storageBucket: 'metqr-ff755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrXD6gfyVSCNYxia-6yYQOr3pICQC33k0',
    appId: '1:706780828460:ios:06c787d41804d895cd9289',
    messagingSenderId: '706780828460',
    projectId: 'metqr-ff755',
    storageBucket: 'metqr-ff755.appspot.com',
    androidClientId: '706780828460-a71p5i6n0ob806ine5ba8jobiur3pe97.apps.googleusercontent.com',
    iosClientId: '706780828460-llo73vdo0l9i835huqopo3fv0otq5esq.apps.googleusercontent.com',
    iosBundleId: 'com.example.metqr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrXD6gfyVSCNYxia-6yYQOr3pICQC33k0',
    appId: '1:706780828460:ios:06c787d41804d895cd9289',
    messagingSenderId: '706780828460',
    projectId: 'metqr-ff755',
    storageBucket: 'metqr-ff755.appspot.com',
    androidClientId: '706780828460-a71p5i6n0ob806ine5ba8jobiur3pe97.apps.googleusercontent.com',
    iosClientId: '706780828460-llo73vdo0l9i835huqopo3fv0otq5esq.apps.googleusercontent.com',
    iosBundleId: 'com.example.metqr',
  );
}
